name: TestLab Record
description: Uploads CI results to TestLab

inputs:
  junit-paths:
    description: Newline-separated list of glob paths to junit files.
    required: false
  repo-root:
    description: Root directory of the repository.
    required: false
  continue-on-error:
    description: Continue with CI workflow on error.
    type: boolean
    required: false
    default: true

runs:
  using: composite
  steps:
    - name: Upload results
      run: ${GITHUB_ACTION_PATH}/script.sh
      shell: bash
      continue-on-error: ${{ fromJSON(inputs.continue-on-error) }}
      env:
        JUNIT_PATHS: ${{ inputs.junit-paths }}
        REPO_ROOT: ${{ inputs.repo-root || github.workspace }}
