name: tidy

on:
  pull_request_target:
    paths:
      - 'go.mod'
      - 'go.sum'

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 2

      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Tidy
        run: go mod tidy

      - name: Commit
        run: |
          set -ue -o pipefail

          git status --porcelain

          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "${GITHUB_ACTOR}"
            git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
            git add .
            git commit --message "Run 'go mod tidy'"
            git push
          else
            echo "No changes to commit."
          fi
