name: tidy

on:
  pull_request_target:
    paths:
      - 'go.mod'
      - 'go.sum'

jobs:
  update:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 2
          token: ${{ secrets.DEPENDABOT_GITHUB_TOKEN }}

      - name: Setup Git
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Tidy
        run: go mod tidy

      - name: Commit
        run: |
          git add .
          if output=$(git status --porcelain) && [ -n "$output" ]; then
            git commit --message "Fix go modules"
            git push
          fi
